/**
 * Cross-implementation guard.
 *
 * There are two engines pricing the same rules now — `tokenlens/pricing.py` for
 * the CLI, this one for the browser. The dangerous failure is not a crash, it is
 * the two of them quietly disagreeing, so the web app and the CLI report
 * different dollar figures for the same log with nothing to say which is right.
 *
 * The fixture is generated by `backend/scripts/export_pricing_golden.py` and
 * holds what Python computes. Every figure here has to match it. If a rate
 * changes, `pricing.yaml` moves, both generators are re-run, and both sides
 * update together — or this goes red.
 *
 * Comparison is numeric, not textual: `Decimal` carries an exponent into its
 * string form ("39.995350") where this engine renders the canonical
 * "39.99535". Equal money, different spelling, and holding the port to Python's
 * exponent bookkeeping would be testing the wrong thing.
 */

import { describe, expect, it } from 'vitest'

import golden from './__fixtures__/pricing-golden.json'
import { parseMoney, sum } from './money'
import type { Money } from './money'
import { makeCall } from './models'
import { TOKEN_CATEGORIES, defaultTable } from './pricing'
import type { TokenCategory } from './pricing'

interface GoldenCase {
  name: string
  model: string
  timestamp: string | null
  tokens: Record<TokenCategory, number>
  resolved_model: string
  tier: number
  promotional: boolean
  cost: string
  breakdown: Record<TokenCategory, string>
  cost_at_tier: Record<string, string>
}

const cases = golden.cases as GoldenCase[]

const callFor = (data: GoldenCase) =>
  makeCall({
    model: data.model,
    timestamp: data.timestamp ? new Date(data.timestamp) : null,
    ...data.tokens,
  })

describe('rate table provenance', () => {
  it('prices against the same table version Python did', () => {
    // A figure is only traceable if both engines can name the table behind it.
    const table = defaultTable()
    expect(table.version).toBe(golden.rate_table.version)
    expect(table.updated).toBe(golden.rate_table.updated)
    expect(table.currency).toBe(golden.rate_table.currency)
  })

  it('covers a meaningful spread of cases', () => {
    // Cheap insurance against a truncated or half-written fixture passing
    // vacuously.
    expect(cases.length).toBeGreaterThanOrEqual(15)
  })
})

describe.each(cases.map((data) => [data.name, data] as const))(
  'golden: %s',
  (_name, data) => {
    const table = defaultTable()
    const call = callFor(data)

    it('resolves to the same rate entry', () => {
      expect(table.resolve(data.model)).toBe(data.resolved_model)
    })

    it('agrees on tier and promotional state', () => {
      const rates = table.ratesFor(call.model, call.timestamp)
      expect(rates.tier).toBe(data.tier)
      expect(rates.promotional).toBe(data.promotional)
    })

    it('agrees on total cost', () => {
      expect(table.costOf(call)).toBe(parseMoney(data.cost))
    })

    it('agrees on every category in the breakdown', () => {
      const breakdown = table.costBreakdown(call)
      for (const category of TOKEN_CATEGORIES) {
        expect(breakdown[category], category).toBe(parseMoney(data.breakdown[category]))
      }
    })

    it('sums the breakdown to the total', () => {
      const breakdown: Money[] = TOKEN_CATEGORIES.map(
        (category) => table.costBreakdown(call)[category],
      )
      expect(sum(breakdown)).toBe(parseMoney(data.cost))
    })

    it('agrees on the counterfactual cost at every tier', () => {
      for (const [tier, expected] of Object.entries(data.cost_at_tier)) {
        expect(table.costAtTier(call, Number(tier)), `tier ${tier}`).toBe(
          parseMoney(expected),
        )
      }
    })
  },
)
